baseURL = 'https://github.com/bunny-thief/tech-bytes.git'
languageCode = 'en-us'
theme = 'inkblotty'
enableEmoji = true

[params]
title = 'Tech Bytes'
author ='Jacques'
decription = 'A tech related blog - Linux, Raspberry pi, programming'

