baseURL = 'https://bunny-thief.github.io/tech-bytes/'
languageCode = 'en-us'
theme = 'inkblotty'
enableEmoji = true
publishdir = "/"
[params]
title = 'Tech Bytes'
author ='Jacques'
decription = 'A tech related blog - Linux, Raspberry pi, programming'
profilePicture = 'images/tb_profile_20220128_234817.jpg'
mainSections = ['blog']
